#!/bin/bash
set -e
VERSION=$(jq -r .version package.json)
VERSION_TAG=$VERSION.b$CIRCLE_BUILD_NUM

export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

docker login -u $DOCKER_USER -p $DOCKER_PASS

docker context ls
# docker buildx create --use --name redash node-amd64
# docker buildx create --append --name redash node-arm64
docker buildx build --platform linux/amd64,linux/arm64 --build-arg skip_dev_deps=true -t petrodzyuba/redash:$VERSION_TAG .
docker push petrodzyuba/redash:$VERSION_TAG

echo "Built: $VERSION_TAG"
